# Generated by Django 4.2.13 on 2024-06-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='car_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='package_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PackageCarRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devanshi_taxi.car')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devanshi_taxi.package')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='cars',
            field=models.ManyToManyField(through='devanshi_taxi.PackageCarRelationship', to='devanshi_taxi.car'),
        ),
    ]
