# Generated by Django 4.2.11 on 2024-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='full_payable_amount',
        ),
    ]
