# Generated by Django 4.2.11 on 2024-07-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='cars',
        ),
        migrations.RemoveField(
            model_name='packagecarrelationship',
            name='car',
        ),
        migrations.RemoveField(
            model_name='packagecarrelationship',
            name='package',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PackageCarRelationship',
        ),
    ]
