# Generated by Django 4.1.13 on 2024-07-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='drop',
            new_name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup',
        ),
    ]
