# Generated by Django 4.1.13 on 2024-07-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0002_rename_drop_booking_pickup_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_address',
            new_name='pickup',
        ),
    ]
