# Generated by Django 4.2.11 on 2024-07-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0002_remove_booking_full_payable_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
