# Generated by Django 4.2.11 on 2024-07-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0003_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
