# Generated by Django 4.2.11 on 2024-07-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0004_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('alt_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('pickup', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('num_passengers', models.IntegerField()),
                ('travel_type', models.CharField(max_length=20)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('route', models.CharField(blank=True, max_length=255, null=True)),
                ('full_payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
