# Generated by Django 4.2.11 on 2024-07-06 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0005_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
