# Generated by Django 4.2.11 on 2024-07-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devanshi_taxi', '0007_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='devanshi_taxi.cars'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
